import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";
import { parse } from "yaml";
import { describe, expect, it } from "vitest";
import type { CityRow, GeoCity, ZipRow } from "./geonames.ts";
import { readPlaces, renderMetrosYaml, writePlaces } from "./files.ts";

const cities: CityRow[] = [
  { id: 4999311, slug: "o-fallon", name: "O'Fallon", state: "MO", lat: 38.81061, lng: -90.69985, population: 91316, timeZone: "America/Chicago" },
  { id: 5126183, slug: "mamaroneck", name: "Mamaroneck", state: "NY", lat: 40.94871, lng: -73.73263, population: 19375, timeZone: "America/New_York" },
];
const zips: ZipRow[] = [
  { zip: "10543", lat: 40.9529, lng: -73.7363, cityId: 5126183, place: "Mamaroneck", state: "NY" },
  { zip: "19035", lat: 40.0436, lng: -75.2801, cityId: null, place: "Gladwyne, Main Line", state: "PA" },
];

describe("places files", () => {
  it("round-trips cities.csv.gz and zips.csv.gz", async () => {
    const dir = await mkdtemp(join(tmpdir(), "gof-places-"));
    await writePlaces(dir, { cities, zips });
    const csv = gunzipSync(await readFile(join(dir, "cities.csv.gz"))).toString("utf8");
    expect(csv.split("\n")[0]).toBe("id,slug,name,state,lat,lng,population,time_zone");
    expect(await readPlaces(dir)).toEqual({ cities, zips });
  });

  it("rejects a corrupt row", async () => {
    const dir = await mkdtemp(join(tmpdir(), "gof-places-"));
    await writePlaces(dir, { cities: [{ ...cities[0]!, lat: 200 }], zips: [] });
    await expect(readPlaces(dir)).rejects.toThrow();
  });
});

describe("renderMetrosYaml", () => {
  it("lists name, state, lat, lng and population with a source note", () => {
    const metros: GeoCity[] = [
      { id: 5128581, name: "New York City", state: "NY", lat: 40.71427, lng: -74.00597, population: 8804190, timeZone: "America/New_York", featureCode: "PPL" },
    ];
    const text = renderMetrosYaml(metros);
    expect(text).toMatch(/^# Generated by `pnpm run places:build`/);
    expect(text).toContain("CC BY 4.0");
    expect(parse(text)).toEqual({
      metros: [{ name: "New York City", state: "NY", lat: 40.71427, lng: -74.00597, population: 8804190 }],
    });
  });
});
