import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { gunzipSync, gzipSync } from "node:zlib";
import { stringify } from "yaml";
import { z } from "zod";
import { isUsStateCode } from "@gof/shared/places";
import { parseCsv, toCsv } from "./csv.ts";
import type { CityRow, GeoCity, ZipRow } from "./geonames.ts";

/** data/places/ (SPEC.md 7.2): GeoNames subsets, generated by `pnpm run places:build`. */
export const CITIES_FILE = "cities.csv.gz";
export const ZIPS_FILE = "zips.csv.gz";
export const METROS_FILE = "metros.yaml";

const CITY_HEADER = ["id", "slug", "name", "state", "lat", "lng", "population", "time_zone"] as const;
const ZIP_HEADER = ["zip", "lat", "lng", "city_id", "place", "state"] as const;

const state = z.string().refine(isUsStateCode, "not a US state code");
const cityRow = z.object({
  id: z.coerce.number().int().positive(),
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  name: z.string().min(1),
  state,
  lat: z.coerce.number().min(-90).max(90),
  lng: z.coerce.number().min(-180).max(180),
  population: z.coerce.number().int().min(0),
  timeZone: z.string().min(3),
});
const zipRow = z.object({
  zip: z.string().regex(/^\d{5}$/),
  lat: z.coerce.number().min(-90).max(90),
  lng: z.coerce.number().min(-180).max(180),
  cityId: z
    .string()
    .transform((v) => (v === "" ? null : Number(v)))
    .pipe(z.number().int().positive().nullable()),
  place: z.string().min(1),
  state,
});

function rowsOf(text: string, header: readonly string[]): string[][] {
  const [head, ...rows] = parseCsv(text);
  if (!head || head.join(",") !== header.join(",")) {
    throw new Error(`unexpected CSV header: ${head?.join(",") ?? "(empty)"}`);
  }
  return rows.filter((r) => r.length > 1 || r[0] !== "");
}

export async function writePlaces(
  dir: string,
  data: { cities: readonly CityRow[]; zips: readonly ZipRow[] },
): Promise<void> {
  await mkdir(dir, { recursive: true });
  const cityCsv = toCsv([
    [...CITY_HEADER],
    ...data.cities.map((c) => [
      String(c.id),
      c.slug,
      c.name,
      c.state,
      String(c.lat),
      String(c.lng),
      String(c.population),
      c.timeZone,
    ]),
  ]);
  const zipCsv = toCsv([
    [...ZIP_HEADER],
    ...data.zips.map((z) => [z.zip, String(z.lat), String(z.lng), z.cityId === null ? "" : String(z.cityId), z.place, z.state]),
  ]);
  // gzip without a timestamp, so the same input gives byte-identical files.
  await writeFile(join(dir, CITIES_FILE), gzipSync(cityCsv, { level: 9 }));
  await writeFile(join(dir, ZIPS_FILE), gzipSync(zipCsv, { level: 9 }));
}

export async function readPlaces(dir: string): Promise<{ cities: CityRow[]; zips: ZipRow[] }> {
  const cityText = gunzipSync(await readFile(join(dir, CITIES_FILE))).toString("utf8");
  const zipText = gunzipSync(await readFile(join(dir, ZIPS_FILE))).toString("utf8");
  const cities = rowsOf(cityText, CITY_HEADER).map((r) =>
    cityRow.parse({
      id: r[0],
      slug: r[1],
      name: r[2],
      state: r[3],
      lat: r[4],
      lng: r[5],
      population: r[6],
      timeZone: r[7],
    }),
  );
  const zips = rowsOf(zipText, ZIP_HEADER).map((r) =>
    zipRow.parse({ zip: r[0], lat: r[1], lng: r[2], cityId: r[3] ?? "", place: r[4], state: r[5] }),
  );
  return { cities, zips };
}

export function renderMetrosYaml(metros: readonly GeoCity[]): string {
  const header = [
    "# Generated by `pnpm run places:build` from GeoNames cities1000 (geonames.org, CC BY 4.0).",
    "# The most populous US cities, used for search-by-place queries (SPEC.md 8.2). Do not edit.",
    "",
  ].join("\n");
  const body = stringify(
    {
      metros: metros.map((m) => ({
        name: m.name,
        state: m.state,
        lat: m.lat,
        lng: m.lng,
        population: m.population,
      })),
    },
    { lineWidth: 0 },
  );
  return header + body;
}

export async function writeMetros(dir: string, metros: readonly GeoCity[]): Promise<void> {
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, METROS_FILE), renderMetrosYaml(metros));
}

export const metroSchema = z.object({
  name: z.string().min(1),
  state,
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  population: z.number().int().min(0),
});
export type Metro = z.infer<typeof metroSchema>;
